package demodata

import (
	"bytes"
	"testing"

	"github.com/spiffcs/hoard/internal/hoardjson"
)

// The document is generated by hoard, by a procedure written down in this
// package's doc comment and run by hand every year or two. That is exactly the
// kind of step that gets done slightly wrong: a merge run without the printings,
// an export from the wrong command, a file truncated on the way in. None of it
// would fail to compile — go:embed takes any bytes — and the symptom would be a
// demo that opens on an empty or blank-looking collection, which is the one
// thing this feature exists to avoid.
func TestCollectionIsAUsableHoardDocument(t *testing.T) {
	h, err := hoardjson.ReadHoard(bytes.NewReader(Collection))
	if err != nil {
		t.Fatalf("embedded collection is not a hoard document: %v", err)
	}

	if len(h.Printings) == 0 {
		t.Fatal("no printings: the demo would open on an empty collection")
	}
	if len(h.Holdings.Rows) == 0 {
		t.Fatal("no holdings: printings without holdings are a catalog, not a collection")
	}

	// A binder and a deck, because the browser's left pane is the feature the
	// demo is showing off and one container makes a poor showcase of it.
	var binders, decks int
	for _, c := range h.Containers {
		switch c.Kind {
		case "binder":
			binders++
		case "deck":
			decks++
		}
	}
	if binders == 0 || decks == 0 {
		t.Errorf("containers = %d binders, %d decks; want at least one of each", binders, decks)
	}

	// Raw is what the browser derives rarity, colour identity, type line and art
	// from — they are generated columns over it. A document whose printings lost
	// Raw still holds, prices and counts correctly, so nothing errors; the cards
	// just render blank in every column the demo is meant to show.
	for _, p := range h.Printings {
		if p.Name == "" {
			t.Errorf("printing %s has no name", p.ScryfallID)
		}
		if len(p.Raw) == 0 {
			t.Errorf("printing %q carries no raw card document; the browser would render it blank", p.Name)
		}
	}

	// Prices are frozen at generation time and drifting is fine, but a document
	// with no prices at all would show a collection worth nothing — and value is
	// the column the demo is selling.
	var priced int
	for _, p := range h.Printings {
		if p.PriceUsd != nil || p.PriceUsdFoil != nil || p.PriceUsdEtched != nil {
			priced++
		}
	}
	if priced == 0 {
		t.Error("no printing carries a price: the demo would value the whole collection at nothing")
	}
}
