package demo

// Seeding a store's price history from a document.
//
// This exists for `hoard demo`, whose Movers view was the one screen a sample
// collection could not show. Movers charts a card against its own past, and a
// database seeded from a document has no past: the view opened empty, and the
// only way to fill it was a ~150 MB MTGJSON download the demo never promised
// to make. A demo that needs the network is a demo that fails on a train, and
// that rule already governs the sample collection itself.
//
// The document is build data, not interchange. It is not one of hoardjson's
// kinds, no command writes it, and nothing outside this repository is expected
// to read it; it is regenerated by internal/demo/gen — `task generate-demo-history` —
// from a real backfill. The import goes through store.BackfillPrices and
// store.BackfillBids
// — the same two calls the live backfill makes — so a seeded series is bounded,
// vendor-retired and finish-normalized by exactly the code a fetched one is,
// and cannot become a second, divergent idea of what recorded history is.

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"

	"github.com/spiffcs/hoard/internal/mtgjson"
	"github.com/spiffcs/hoard/internal/store"
)

// HistoryKind is the document's self-declared kind, checked on read so a file
// pointed at this by mistake fails with a sentence rather than seeding nothing.
const HistoryKind = "demo-price-history"

// HistoryPoint is one dated observation. Date is 'YYYY-MM-DD', the archive's
// own granularity — the store stamps it to midnight, which is what keeps a
// reconstructed point behind any live one taken the same day.
type HistoryPoint struct {
	Date  string  `json:"date"`
	Price float64 `json:"price"`
}

// HistorySeries is one card's observations in one finish, from one vendor.
//
// Finish and Source are on the series rather than the point because that is
// what they are: the archive reader picks a single vendor per card and finish
// and takes its series whole, never splicing two. A document that carried them
// per point could describe a spliced series, which is a thing hoard refuses to
// record.
type HistorySeries struct {
	ScryfallID string         `json:"scryfallId"`
	Finish     string         `json:"finish"`
	Source     string         `json:"source"`
	Points     []HistoryPoint `json:"points"`
}

// HistoryDocument is a pre-computed backfill: the retail series and the
// buylist bids behind them, as one file.
type HistoryDocument struct {
	Kind string `json:"kind"`
	// GeneratedAt is when the series were read, for the reader who wants to
	// know how frozen "frozen" is.
	GeneratedAt string          `json:"generatedAt"`
	Retail      []HistorySeries `json:"retail"`
	Bids        []HistorySeries `json:"bids,omitempty"`
}

// SeedHistoryResult is what a seeded document put into the two tables.
type SeedHistoryResult struct {
	Inserted, Cards       int
	BidInserted, BidCards int
	// GeneratedAt is the document's own stamp, passed through so the caller can
	// say how old the sample is.
	GeneratedAt string
}

// ReadHistory parses a history document without applying it.
func ReadHistory(r io.Reader) (HistoryDocument, error) {
	var doc HistoryDocument
	if err := json.NewDecoder(r).Decode(&doc); err != nil {
		return doc, fmt.Errorf("reading price history: %w", err)
	}
	if doc.Kind != HistoryKind {
		return doc, fmt.Errorf("not a %s document: kind is %q", HistoryKind, doc.Kind)
	}
	return doc, nil
}

// SeedHistory records a document's observations into a store.
//
// The destination is assumed to hold the printings the document names — the
// import filters against the finishes each printing is actually sold in, so a
// series for a card the store has never seen is silently dropped rather than
// inserted against nothing.
func SeedHistory(st *store.Store, doc HistoryDocument) (SeedHistoryResult, error) {
	out := SeedHistoryResult{GeneratedAt: doc.GeneratedAt}
	var err error
	if out.Inserted, out.Cards, err = st.BackfillPrices(observations(doc.Retail)); err != nil {
		return out, fmt.Errorf("recording sample price history: %w", err)
	}
	if out.BidInserted, out.BidCards, err = st.BackfillBids(observations(doc.Bids)); err != nil {
		return out, fmt.Errorf("recording sample buylist history: %w", err)
	}
	return out, nil
}

// SeedEmbeddedHistory records the compiled-in history into a store.
//
// The parse failure is wrapped where it happens rather than at the call site: a
// document that does not read is a build that shipped a broken file, not
// anything the user did or can fix, and the sentence should say so.
func SeedEmbeddedHistory(st *store.Store) (SeedHistoryResult, error) {
	doc, err := ReadHistory(bytes.NewReader(History))
	if err != nil {
		return SeedHistoryResult{}, fmt.Errorf("the built-in sample price history: %w", err)
	}
	return SeedHistory(st, doc)
}

// TopUpHistory gives an already-built demo the history it was made without, and
// reports whether it did.
//
// Every demo database created before the history was compiled in has none, and
// nothing else would ever put one there: seeding runs only on a database that
// did not exist, so those readers would open an empty movers view forever
// unless they happened to know --reset rebuilds the sample.
//
// The guard is the history being empty, not the file's age. A demo whose owner
// has backfilled it for real must never have frozen sample rows laid underneath
// live ones, and "has no history at all" is the only condition that cannot be
// true of one.
func TopUpHistory(st *store.Store) (res SeedHistoryResult, seeded bool, err error) {
	obs, _, err := st.PriceHistoryDepth()
	if err != nil || obs > 0 {
		return SeedHistoryResult{}, false, err
	}
	res, err = SeedEmbeddedHistory(st)
	if err != nil {
		return SeedHistoryResult{}, false, err
	}
	return res, res.Inserted+res.BidInserted > 0, nil
}

// observations flattens the document's series into the shape the store's two
// backfills take.
func observations(series []HistorySeries) map[string][]mtgjson.Observation {
	if len(series) == 0 {
		return nil
	}
	byCard := map[string][]mtgjson.Observation{}
	for _, s := range series {
		for _, p := range s.Points {
			byCard[s.ScryfallID] = append(byCard[s.ScryfallID], mtgjson.Observation{
				Date: p.Date, Finish: s.Finish, Price: p.Price, Source: s.Source,
			})
		}
	}
	return byCard
}
