// Package schemagen derives the SQL under schema/sqlite/ from the migrations
// themselves, so the published schema cannot drift from the one hoard actually
// creates: migrate.go is the source of truth, the generator migrates a scratch
// database and dumps it, and a test regenerates and compares.
//
// This is the SQLite counterpart to internal/hoardjson/schemagen, and follows
// the same rule — the code is authoritative, the checked-in file is a
// convenience for anyone reading hoard's data without running hoard.
//
// It is a separate package from store so the hoard binary, which imports store
// on every command, never links the dump machinery.
package schemagen

import (
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/spiffcs/hoard/internal/store"
)

// RepoRoot locates the repository root from this file's compiled position, so
// the generator and the drift test resolve the same paths whatever their
// working directory.
func RepoRoot() string {
	_, file, _, _ := runtime.Caller(0)
	return filepath.Clean(filepath.Join(filepath.Dir(file), "..", "..", ".."))
}

// object is one row of sqlite_master worth publishing.
type object struct {
	kind string // "table" or "index"
	name string
	sql  string
}

// Generate migrates an empty database to the current version and returns its
// schema as formatted SQL.
//
// A scratch file rather than :memory: because migrate() backs the database up
// before it works, which needs a real path — and exercising that path here
// means the generator fails loudly if the backup ever breaks, rather than
// silently describing a schema no user can reach.
func Generate() ([]byte, error) {
	dir, err := os.MkdirTemp("", "hoard-schema")
	if err != nil {
		return nil, err
	}
	defer os.RemoveAll(dir)

	path := filepath.Join(dir, "schema.db")
	s, err := store.Open(path)
	if err != nil {
		return nil, fmt.Errorf("migrating scratch database: %w", err)
	}
	if err := s.Close(); err != nil {
		return nil, err
	}

	db, err := sql.Open("sqlite", path)
	if err != nil {
		return nil, err
	}
	defer db.Close()

	objs, err := readObjects(db)
	if err != nil {
		return nil, err
	}
	var userVersion int
	if err := db.QueryRow(`PRAGMA user_version`).Scan(&userVersion); err != nil {
		return nil, err
	}
	return render(objs, userVersion), nil
}

// readObjects reads every schema object worth publishing, ordered tables first
// then indexes, each group by name — a stable order the source file's own
// ordering cannot give, since migrations add columns and tables over time.
//
// sqlite_sequence is skipped: SQLite creates and maintains it for AUTOINCREMENT
// and nothing in hoard's model refers to it.
func readObjects(db *sql.DB) ([]object, error) {
	rows, err := db.Query(`
SELECT type, name, sql FROM sqlite_master
WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%'`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var objs []object
	for rows.Next() {
		var o object
		if err := rows.Scan(&o.kind, &o.name, &o.sql); err != nil {
			return nil, err
		}
		objs = append(objs, o)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	sort.Slice(objs, func(i, j int) bool {
		if objs[i].kind != objs[j].kind {
			return objs[i].kind == "table"
		}
		return objs[i].name < objs[j].name
	})
	return objs, nil
}

// render writes the dump: a header naming the version, then each object.
func render(objs []object, userVersion int) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, `-- hoard.db schema, version %d.
--
-- Generated by "make generate-sqlite-schema" from the migrations in
-- internal/store/migrate.go, which are the source of truth. Do not edit:
-- a drift test fails if this file and the migrations disagree.
--
-- A migrated database carries this version in PRAGMA user_version, and
-- PRAGMA application_id 0x484F5244 ("HORD") identifies the file as hoard's.
--
-- See schema/sqlite/README.md for the compatibility rules.
`, userVersion)

	for _, o := range objs {
		b.WriteString("\n")
		b.WriteString(format(o.sql))
		b.WriteString(";\n")
	}
	return []byte(b.String())
}

// format re-lays a CREATE statement one column per line.
//
// SQLite stores a table's DDL as the original CREATE text with every later
// ALTER TABLE ADD COLUMN appended to the end, so a table grown over twenty
// migrations dumps as one unreadable line with the newest columns crammed
// after the closing paren of the oldest. Splitting the body on its top-level
// commas and re-indenting gives a file worth reading, and does it the same way
// every time so the drift test compares like with like.
//
// Anything that is not a parenthesised CREATE (an index, say) is returned with
// its internal whitespace collapsed and nothing else changed.
func format(stmt string) string {
	stmt = strings.TrimSpace(stmt)
	open := strings.Index(stmt, "(")
	close := strings.LastIndex(stmt, ")")
	if open < 0 || close < open {
		return collapse(stmt)
	}
	head := collapse(stmt[:open])
	body := stmt[open+1 : close]

	parts := splitTopLevel(body)
	// A single-part body is an index or a one-column table: three lines to say
	// what fits on one.
	if len(parts) < 2 {
		return collapse(stmt)
	}
	var b strings.Builder
	b.WriteString(head)
	b.WriteString(" (\n")
	for i, p := range parts {
		b.WriteString("    ")
		b.WriteString(collapse(p))
		if i < len(parts)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString(")")
	return b.String()
}

// splitTopLevel splits on commas outside parentheses and outside quotes, so a
// generated column's json_extract(...) arguments and a DEFAULT 'a,b' stay whole.
func splitTopLevel(s string) []string {
	var parts []string
	depth, start := 0, 0
	var quote rune
	for i, r := range s {
		switch {
		case quote != 0:
			if r == quote {
				quote = 0
			}
		case r == '\'' || r == '"':
			quote = r
		case r == '(':
			depth++
		case r == ')':
			depth--
		case r == ',' && depth == 0:
			parts = append(parts, s[start:i])
			start = i + 1
		}
	}
	parts = append(parts, s[start:])

	out := parts[:0]
	for _, p := range parts {
		if p = strings.TrimSpace(p); p != "" {
			out = append(out, p)
		}
	}
	return out
}

// collapse reduces every run of whitespace to a single space.
func collapse(s string) string {
	return strings.Join(strings.Fields(s), " ")
}
