package command

import (
	"io"

	"github.com/spf13/cobra"

	"github.com/spiffcs/hoard/internal/cli"
	"github.com/spiffcs/hoard/internal/ui"
)

// DocTree returns the command tree for documentation generators.
//
// It exists because the tree is the only honest source for reference docs —
// hand-written man pages drift from the flags that exist, and the shell
// completions are generated from this same tree for exactly that reason. The
// alternative was exporting buildRoot, which would invite callers to execute a
// tree whose app is deliberately unfilled.
//
// Nothing here opens a database. The store is attached by the root's
// PersistentPreRunE, which only runs under Execute, and a generator never gets
// that far: it walks Use, Short, Long, Example and the flag sets, all of which
// are fixed at construction time. The streams are io.Discard rather than the
// process's for the same reason — a doc build must not write to stdout by
// accident, since a generator's own output often is stdout.
//
// The width is pinned at 80 instead of detected. A man page rendered against
// whatever terminal happened to run the release build would differ between the
// maintainer's laptop and CI, and reference output that changes with the
// window it was built in is not reference output.
func DocTree() *cobra.Command {
	fixed := func(io.Writer) ui.Env { return ui.Env{Width: 80} }
	a := &app{env: &cli.Env{
		Out: io.Discard, Err: io.Discard,
		OutEnv: fixed(io.Discard), ErrEnv: fixed(io.Discard),
	}}
	root, _ := buildRoot(a, fixed)

	// Cobra otherwise stamps "Auto generated by spf13/cobra on <today>" into
	// every page, which makes two builds of the same commit differ. The build
	// is reproducible everywhere else — -trimpath, pinned tools, a version
	// stamped from the tag — and a date nobody asked for should not be the one
	// thing that breaks it.
	root.DisableAutoGenTag = true
	return root
}
