// Command genman writes hoard's man pages from its own cobra tree.
//
// Build machinery, not a hoard command: it lives under internal/ so it can
// import the command tree, and so `go install ./...` never puts it on anyone's
// PATH. GoReleaser runs it from the before-hooks alongside the completion
// generators, and the pages ride in the release archive.
//
// Generated rather than checked in, for the reason the completions are: a page
// describing a flag that no longer exists is worse than no page, and the only
// way to be sure it cannot happen is to derive the text from the tree the
// binary actually parses.
//
//	go run ./internal/tools/genman manpages
package main

import (
	"fmt"
	"os"

	"github.com/spf13/cobra/doc"

	"github.com/spiffcs/hoard/internal/command"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: genman <output-dir>")
		os.Exit(2)
	}
	dir := os.Args[1]

	if err := os.MkdirAll(dir, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "genman:", err)
		os.Exit(1)
	}

	// Section 1 is user commands. Title is upper-cased by convention in the
	// .TH line; Source and Manual are what `man` prints in the page's footer
	// and header respectively, and left to cobra's defaults they read
	// "Auto generated by spf13/cobra".
	//
	// Date is left nil on purpose: cobra fills it from $SOURCE_DATE_EPOCH when
	// that is set and from the wall clock when it is not, which is exactly the
	// behavior wanted. The release sets it to the commit's timestamp, so the
	// pages in a tag's archive are byte-identical however often it is rebuilt,
	// while a developer running this by hand still gets today's date.
	header := &doc.GenManHeader{
		Title:   "HOARD",
		Section: "1",
		Source:  "hoard",
		Manual:  "hoard Manual",
	}

	if err := doc.GenManTree(command.DocTree(), header, dir); err != nil {
		fmt.Fprintln(os.Stderr, "genman:", err)
		os.Exit(1)
	}
}
