name: "Validate GitHub Actions"

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    name: "Lint"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # required for SARIF upload
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: "Run zizmor"
        uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
        with:
          config: .github/zizmor.yml
          advanced-security: false
          inputs: .github
